default: check test

fmt:
    cargo +nightly fmt --all

check: fmt
    cargo +nightly clippy --workspace --all-targets --all-features -- -D warnings -A dead_code

test:
    cargo test --workspace

[working-directory: 'sir/sir-solidity-diff-tests']
test-sir-diff:
     forge test --ffi

[working-directory: 'plank-diff-tests/']
test-plank-diff *args:
     PLANK_BACKEND=sir PLANK_OPTIMIZE=csud forge test --ffi {{args}}
     PLANK_BACKEND=sona PLANK_OPTIMIZE=csud forge test --ffi {{args}}

[working-directory: 'plank-diff-tests/']
test-plank-diff-sir *args:
     PLANK_BACKEND=sir PLANK_OPTIMIZE=csud forge test --ffi {{args}}

[working-directory: 'plank-diff-tests/']
test-plank-diff-sona *args:
     PLANK_BACKEND=sona PLANK_OPTIMIZE=csud forge test --ffi {{args}}

test-all: test test-sir-diff test-plank-diff

ci-fmt:
    (cd sir/sir-solidity-diff-tests/ && forge fmt --check)
    cargo +nightly fmt --all --check

ci-clippy:
    cargo +nightly clippy --workspace --all-targets --all-features -- -D warnings

ci-all: test-all ci-clippy ci-fmt

docs-build:
    mdbook build ../plank-doc -d ~/.plank/share/doc

docs-serve:
    mdbook serve ../plank-doc
